version: '3.8'
services:
  frontend:
    build:
      context: .
      dockerfile: ./front/Dockerfile
    ports:
      - '3000:3000'
    restart: always
  back:
    build:
      context: .
      dockerfile: ./back/Dockerfile
    ports:
      - '5000:5000'
    restart: always